spring.application.name=apigateway
server.port=8080

# configuracoes do eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# rotas automaticas desativadas
spring.cloud.gateway.server.webflux.discovery.locator.enabled=false

# para fazer requisicao com letras minusculas
# spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# chave para ler o token
# api.jwt.secret=CHAVE_SECRETA

# definicao de rotas
# rota para ms auth (publica sem filtro)
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://PROFESSORES.AUTH
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**

# rota para ms docentes (protegida com filtro JWT)
spring.cloud.gateway.routes[1].id=academico-service
spring.cloud.gateway.routes[1].uri=lb://ms-academico
spring.cloud.gateway.routes[1].predicates[0]=Path=/academico/**
spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter